site_name: FROM FAB LABS TO FAB CITIES
site_description: Training programs & Advisory Services
site_author: Fab Lab Barcelona
site_url: https://fablabbcn.github.io/digifab/
repo_name: digifab
repo_url: https://github.com/fablabbcn/digifab

nav:
  - Main:
      - Welcome: index.md
  - Modulo 1:
      - Intro Fablabs: modulo_1/fablabs.md
      - Presentaciones: modulo_1/presentaciones.md
  - Modulo 2:
      - Intro Fab City: modulo_2/fabcity.md
      - Proyectos: modulo_2/presentaciones.md
  - Modulo 3:
      - Explorando futuros emergentes: modulo_3/aows.md
      - Recursos: modulo_3/recursos.md
  - Modulo 4:
      - Fabricación digital: modulo_4/intro.md
      - Dia 1:Introducción a Git: modulo_4/git.md
      - Dia 2:Modelado 2D/3D: modulo_4/biomaterials.md
      - Dia 3:Fabricación Aditiva: modulo_4/arduino.md
      - Dia 4:Electronica básica: modulo_4/arduino.md
      - Dia 5:Bio Materiales: modulo_4/biomaterials.md
      - Dia 5:PCB: modulo_4/git.md
      - Dia 6:CNC: modulo_4/biomaterials.md
  - Modulo 5:
      - Impact Accelerator: modulo_5/challenge.md
      - Proyectos: modulo_5/recursos.md

theme:
  language: 'en'
  name: 'material'

  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips

  custom_dir: 'custom_theme'
  palette:
    # See assets/stylesheets/extra.css file for the color definitions
    # Palette toggle for light mode
    - scheme: mdef
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  # Logo is not yet available
  # logo: 'assets/images/logo.svg'
  # favicon: 'assets/images/favicon.ico'
  icon:
    repo: fontawesome/brands/git-alt

extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/fablabbcn'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/fablabbcn/'
    - icon: fontawesome/brands/github
      link: 'https://www.github.com/fablabbcn/'
  # project: ''
  # footer_logo: '/assets/images/eu-flag.png'
  fullscreen_button: true

plugins:
  - macros
  - search

markdown_extensions:
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'
  - 'assets/javascripts/extra.js'
